In [2]:
#1. core data structures in pandas: 

#a. Series — 1D Labeled Array: A Series is like a list with labels (index)
import pandas as pd
s = pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
s = pd.Series([10, 20, 30, 40, 50], index= ["Bhanu", "Aditya", "harry", "Swati", "dhruv"]) #You can also define custom index
print(s)

Bhanu     10
Aditya    20
harry     30
Swati     40
dhruv     50
dtype: int64

In [4]:
#b. DataFrame — 2D Labeled Table: A DataFrame is like a dictionary of Series — multiple columns with labels.

data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Bangalore"]
}
 
df = pd.DataFrame(data)

In [5]:
df

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [6]:
df.index = ["a", "b", "c"]  #changes default indexes to a, b and c 
df.columns = ["Name", "Age", "City"] #changes columns with changing capital letter

In [17]:
df

      Name  Age       City
a    Alice   25      Delhi
b      Bob   30     Mumbai
c  Charlie   35  Bangalore

In [22]:
#2. creating dataframes from different method:

#1. From Python Lists:

import pandas as pd
 
data = [
    ["Alice", 25],      #these are list of lists
    ["Bob", 30],
    ["Charlie", 35]
]
 
df = pd.DataFrame(data, columns= ["Names","Age"])

In [23]:
df

     Names  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [25]:
#2. From Dictionary of Lists:

data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [30, 40, 50]
}
df = pd.DataFrame(data)

In [26]:
df

      Name  Age
0    Alice   30
1      Bob   40
2  Charlie   50

In [7]:
#3. From NumPy Arrays:

import numpy as np
arr = np.array([[1,2], [3,4]])
df = pd.DataFrame(arr, columns=["A", "B"])

In [8]:
df

   A  B
0  1  2
1  3  4