In [2]:
import pandas as pd
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values("Year") #automatically ascending order mein change ho jayega

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df.sort_values("Year", ascending = False) #ab descending mein change ho jayega and note that indexees bhi shift ho chuke hain

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [6]:
df.sort_values(["Year", "IMDb"]) 
#df.sort_values([“Year”, “IMDb”]) sorts the DataFrame first by the “Year” column, andif there are ties (i.e., two or more rows with the same “Year”), it will sort by the“IMDb” column

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [7]:
#If you want the index to start from 0 and be sequential, you can reset it using reset_index()
df.reset_index(drop = True)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df.reset_index(drop=True, inplace=True) # If you want to Reset the index and drop the old index (like copy nhi direct view hi chnge krna hai to inplace= True)krde

In [9]:
df #Ab original table bhi change ho gya "inplace = True" ki help se

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [15]:
df["Rank"] = df["IMDb"].rank(ascending = False)  #it provides new column named "Rank" jo highest number/rank to highest IMDb dega

In [20]:
df.sort_values("Rank")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0

In [25]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [38]:
#Renaming Columns & Index
df.rename(columns={"Actor": "Star Name"}, inplace=True)

In [39]:
df

,Star Name,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank,rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0,11.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0,7.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0,10.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0,1.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0,8.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0,5.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0,4.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0,3.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0,6.0

In [41]:
#Changing Column Order: Just pass a new list of column names:
df = df[["Star Name", "Year", "Film", "IMDb"]] # Reorder as desired

In [42]:
df

             Star Name  Year                      Film  IMDb
0       Shah Rukh Khan  2023                   Pathaan   7.2
1          Salman Khan  2017           Tiger Zinda Hai   6.0
2           Aamir Khan  2016                    Dangal   8.4
3        Ranbir Kapoor  2022                Brahmastra   5.6
4        Ranveer Singh  2018                 Padmaavat   7.0
5   Ayushmann Khurrana  2018                 Andhadhun   8.3
6        Rajkummar Rao  2018                     Stree   7.5
7       Hrithik Roshan  2019                       War   6.5
8         Akshay Kumar  2019                Good Newwz   7.0
9        Kartik Aaryan  2022         Bhool Bhulaiyaa 2   5.9
10        Varun Dhawan  2017     Badrinath Ki Dulhania   6.1
11       Vicky Kaushal  2019  Uri: The Surgical Strike   8.2