In [1]:
#we can say series is 1D: beacuse series mein item find krne ke liye hamein sirf ek parameter ki zarorat hai, 
#and dataframe is 2D: beacuse dataframne mein item find krne liye hamein 2 parameters ki zaroorat hai.

In [21]:
#creating multiindex object:

# a. multiindex series:


#1. pd.MultiIndex.from_tuples():
import pandas as pd
index_val = [("cse", 2019), ("cse", 2020), ("cse", 2021), ("cse", 2022), ("ece", 2019), ("ece", 2020), ("ece", 2021), ("ece", 2022)] #list ke andar tuples
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels  # .levels decouple krdega multiindex ko vo branch (cse and ece) ko ek group mein and year (2019-22) ko ek group mein

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [6]:
#2. pd.MultiIndex.from_product():

pd.MultiIndex.from_product([["cse", "ece"], [2019, 2020, 2021, 2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [12]:
# creating a series with multiindex object:

p = pd.Series([1,2,3,4,5,6,7,8], index = multiindex)
p

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [19]:
# unstack : used to convert multiindex series into dataframe:

temp = p.unstack()  #jo upar p hai,uska andar vaala index hai vo column mein convert ho gya
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [20]:
# stack(): used to revert back:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [22]:
# whole idea behind multiindex is ki aap kitne bhi higher dimension data(5D,10D,12D etc) ko series ynn dataframe mein convert kr skte ho,  that =s the whole idea behind learning thsi

#b. Multiindex dataframe:

branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16]
    ],
    index = multiindex,
    columns = ["Avg_package", "students"]
)

branch_df1

          Avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [26]:
branch_df1.loc["cse"] # .loc for fetching us specific rows

      Avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [27]:
branch_df1["Avg_package"]  # for fetching us column, noi need for .loc or .iloc

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: Avg_package, dtype: int64

In [46]:
# very imp: multiindex df from column perspective:

branch_df2 = pd.DataFrame(
    [
        [2,4,6,2],       # yeh 4x4  ka data hai 
        [3,2,5,3],
        [2,5,8,9],
        [4,5,5,2]
    ],
    index = [2019, 2020, 2021, 2022],
    columns = pd.MultiIndex.from_product([["Delhi", "Mumbai"], ["Avg_package", "Students"]])
)

branch_df2  
# its an 3d data object which is in form of dataframe kyunki pandas index and column ko alag alag nhi maanta
# and isme rows to single hi hai but column multiindex hai means column ke upar column which make it 3D data

           Delhi               Mumbai
     Avg_package Students Avg_package Students
2019           2        4           6        2
2020           3        2           5        3
2021           2        5           8        9
2022           4        5           5        2

In [42]:
branch_df2["Delhi"]

      Avg_package  Students
2019            2         4
2020            3         2
2021            2         5
2022            4         5

In [43]:
branch_df2["Mumbai"]["Avg_package"][2020]

np.int64(5)

In [44]:
branch_df2.loc[2019]   #agar aapko specific yearv mein dono cities ka data chahiye to .loc lagayo as hum 2019 as row hi fetch kr rhe hain

Delhi   Avg_package    2
        Students       4
Mumbai  Avg_package    6
        Students       2
Name: 2019, dtype: int64

In [48]:
#very very imp topic: multiindexoing df from both index and columns:

branch_df3 = pd.DataFrame(
    [
        [2,4,6,2],       # yeh 8x8 ka data hai
        [3,2,5,3],
        [2,5,8,9],
        [4,5,5,2],
        [5,6,1,7],
        [2,5,6,4],
        [2,4,6,8],
        [4,2,1,8]
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([["Delhi", "Mumbai"], ["Avg_package", "Students"]])
)

branch_df3 
#ab isme rows and columns dono mein multiindexing ho rhi hai which makes it 4D data

               Delhi               Mumbai
         Avg_package Students Avg_package Students
cse 2019           2        4           6        2
    2020           3        2           5        3
    2021           2        5           8        9
    2022           4        5           5        2
ece 2019           5        6           1        7
    2020           2        5           6        4
    2021           2        4           6        8
    2022           4        2           1        8

In [63]:
# Stacking and unstacking in multidimensional data:
#a. 

branch_df1

          Avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [75]:
branch_df1.unstack()   
# ab .unstack se jo level 1 (means andar vaala) vaala index hai which years (2019 - 22) vo column ban jaayega
# kunki unstack mein index column ban jaata hai

    Avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [57]:
branch_df1.unstack().unstack()

Avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [58]:
type(branch_df1.unstack().unstack())  # to ab yeh series mein change ho jjayegi

pandas.core.series.Series

In [67]:
branch_df1.unstack().stack()
#because stack mein column index ban jaata hai

C:\Users\adity\AppData\Local\Temp\ipykernel_11344\1140920855.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

          Avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [64]:
#b.

branch_df2

           Delhi               Mumbai
     Avg_package Students Avg_package Students
2019           2        4           6        2
2020           3        2           5        3
2021           2        5           8        9
2022           4        5           5        2

In [68]:
branch_df2.unstack()   # as ek hi index tha , to unstack lagane se vo bhi column bangya  and overall yeh series ban gyi

Delhi   Avg_package  2019    2
                     2020    3
                     2021    2
                     2022    4
        Students     2019    4
                     2020    2
                     2021    5
                     2022    5
Mumbai  Avg_package  2019    6
                     2020    5
                     2021    8
                     2022    5
        Students     2019    2
                     2020    3
                     2021    9
                     2022    2
dtype: int64

In [70]:
branch_df2.stack()   #as ab level 1 ka column i.e avg_package and students vaala column index ban jaayega and yeh dataframe ban jayega

C:\Users\adity\AppData\Local\Temp\ipykernel_11344\1163818577.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack()   #as ab level 1 ka column i.e avg_package and students vaala column index ban jaayega and yeh dataframe ban jayega

                  Delhi  Mumbai
2019 Avg_package      2       6
     Students         4       2
2020 Avg_package      3       5
     Students         2       3
2021 Avg_package      2       8
     Students         5       9
2022 Avg_package      4       5
     Students         5       2

In [71]:
branch_df2.stack().stack()    # ab delhi and mumbai vaala column bhi index mein aa jaayega so yeh series ban jaayegi finally

C:\Users\adity\AppData\Local\Temp\ipykernel_11344\1903088298.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack().stack()    # ab delhi and mumbai vaala column bhi index mein aa jaayega so yeh series ban jaayegi finally

2019  Avg_package  Delhi     2
                   Mumbai    6
      Students     Delhi     4
                   Mumbai    2
2020  Avg_package  Delhi     3
                   Mumbai    5
      Students     Delhi     2
                   Mumbai    3
2021  Avg_package  Delhi     2
                   Mumbai    8
      Students     Delhi     5
                   Mumbai    9
2022  Avg_package  Delhi     4
                   Mumbai    5
      Students     Delhi     5
                   Mumbai    2
dtype: int64

In [72]:
#c. 

branch_df3

               Delhi               Mumbai
         Avg_package Students Avg_package Students
cse 2019           2        4           6        2
    2020           3        2           5        3
    2021           2        5           8        9
    2022           4        5           5        2
ece 2019           5        6           1        7
    2020           2        5           6        4
    2021           2        4           6        8
    2022           4        2           1        8

In [73]:
branch_df3.unstack()

          Delhi                                             Mumbai            \
    Avg_package                Students                Avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           2    3    2    4        4    2    5    5           6    5    8
ece           5    2    2    4        6    5    4    2           1    6    6


         Students
    2022     2019 2020 2021 2022
cse    5        2    3    9    2
ece    1        7    4    8    8

In [74]:
branch_df3.unstack().unstack()

Delhi   Avg_package  2019  cse    2
                           ece    5
                     2020  cse    3
                           ece    2
                     2021  cse    2
                           ece    2
                     2022  cse    4
                           ece    4
        Students     2019  cse    4
                           ece    6
                     2020  cse    2
                           ece    5
                     2021  cse    5
                           ece    4
                     2022  cse    5
                           ece    2
Mumbai  Avg_package  2019  cse    6
                           ece    1
                     2020  cse    5
                           ece    6
                     2021  cse    8
                           ece    6
                     2022  cse    5
                           ece    1
        Students     2019  cse    2
                           ece    7
                     2020  cse    3
                           ece    4
                     2021  cse    9
                           ece    8
                     2022  cse    2
                           ece    8
dtype: int64

In [76]:
branch_df3.stack()

C:\Users\adity\AppData\Local\Temp\ipykernel_11344\4148153360.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df3.stack()

                      Delhi  Mumbai
cse 2019 Avg_package      2       6
         Students         4       2
    2020 Avg_package      3       5
         Students         2       3
    2021 Avg_package      2       8
         Students         5       9
    2022 Avg_package      4       5
         Students         5       2
ece 2019 Avg_package      5       1
         Students         6       7
    2020 Avg_package      2       6
         Students         5       4
    2021 Avg_package      2       6
         Students         4       8
    2022 Avg_package      4       1
         Students         2       8

In [77]:
branch_df3.stack().stack()

C:\Users\adity\AppData\Local\Temp\ipykernel_11344\4023844418.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df3.stack().stack()

cse  2019  Avg_package  Delhi     2
                        Mumbai    6
           Students     Delhi     4
                        Mumbai    2
     2020  Avg_package  Delhi     3
                        Mumbai    5
           Students     Delhi     2
                        Mumbai    3
     2021  Avg_package  Delhi     2
                        Mumbai    8
           Students     Delhi     5
                        Mumbai    9
     2022  Avg_package  Delhi     4
                        Mumbai    5
           Students     Delhi     5
                        Mumbai    2
ece  2019  Avg_package  Delhi     5
                        Mumbai    1
           Students     Delhi     6
                        Mumbai    7
     2020  Avg_package  Delhi     2
                        Mumbai    6
           Students     Delhi     5
                        Mumbai    4
     2021  Avg_package  Delhi     2
                        Mumbai    6
           Students     Delhi     4
                        Mumbai    8
     2022  Avg_package  Delhi     4
                        Mumbai    1
           Students     Delhi     2
                        Mumbai    8
dtype: int64

In [79]:
branch_df3

               Delhi               Mumbai
         Avg_package Students Avg_package Students
cse 2019           2        4           6        2
    2020           3        2           5        3
    2021           2        5           8        9
    2022           4        5           5        2
ece 2019           5        6           1        7
    2020           2        5           6        4
    2021           2        4           6        8
    2022           4        2           1        8

In [80]:
# extracting single row:

branch_df3.loc[("cse", 2021)]

Delhi   Avg_package    2
        Students       5
Mumbai  Avg_package    8
        Students       9
Name: (cse, 2021), dtype: int64

In [81]:
#extracting columnn:
branch_df3["Delhi"]

          Avg_package  Students
cse 2019            2         4
    2020            3         2
    2021            2         5
    2022            4         5
ece 2019            5         6
    2020            2         5
    2021            2         4
    2022            4         2

In [82]:
#extracting single column:

branch_df3["Delhi"]["Avg_package"]

cse  2019    2
     2020    3
     2021    2
     2022    4
ece  2019    5
     2020    2
     2021    2
     2022    4
Name: Avg_package, dtype: int64

In [86]:
# extracting multiple column like delhi ka Avg_package and mumbai ka students ke column nikaalna hai, to iloc better rehta hai loc se kyunki iloc mein direct indexes assign krne hai

branch_df3.iloc[:, 0:4:3]   # pehla : matlab saare rows chahiye indexes ke and column 0 se 4( which is not included) with gap of 2

               Delhi   Mumbai
         Avg_package Students
cse 2019           2        2
    2020           3        3
    2021           2        9
    2022           4        2
ece 2019           5        7
    2020           2        4
    2021           2        8
    2022           4        8

In [88]:
#agar cse and ece dono ka 1st row and delhi ka students and mumbai ka avg_package ka column find krna hai:

branch_df3.iloc[0:8:4, 1:3]  #method 1 agar paatern fing krliya nhi to

            Delhi      Mumbai
         Students Avg_package
cse 2019        4           6
ece 2019        6           1

In [90]:
# method 2 : better hai as "fancy indexing" jo index chahiye directly daaldo, isme list mein list pass krte hain

branch_df3.iloc[[0,4],[1,2]]  # yahaan logic lagane ki koi need nhi hai direct jo rows yn column chaahiye uske direct index lagado

            Delhi      Mumbai
         Students Avg_package
cse 2019        4           6
ece 2019        6           1