In [1]:
import pandas as pd
df = pd.read_csv("data_cleaning_sample.csv")

In [3]:
#FileNotFoundError: [Errno 2] No such file or directory: 'data_cleaning_sample.csv' so always use below method:
import os
print(os.getcwd())  #Check the current working directory

C:\Users\adity\Favorites

In [4]:
import os
print(os.listdir()) #Check if the file is actually there

['.ipynb_checkpoints', 'Bing.url', 'data.csv', 'data.json', 'data2.json', 'data2_clean', 'desktop.ini', 'initial_data.txt', 'Links', 'massive_data.json', 'numpy_indexing.ipynb', 'numpy_module.ipynb', 'pandas_Data Cleaning & Preprocessing.ipynb', 'pandas_Data Selection & Filtering.ipynb', 'pandas_module.ipynb', 'proj1_a_intro.ipynb', 'proj1_b_dataclean.ipynb', 'proj1_c_people_know.ipynb', 'proj1_d_pages_like.ipynb', 'proj2_a_parsingdata.ipynb']

In [1]:
#now you know that "C:\Users\adity\Favorites" is original path so, copy that file  which is in download section in your pc and poste in that particular path i.e. in folder name datasets (C:\Users\adity\Favorites\datasets), so automatically it shows left side of this jupyter lab
import pandas as pd
df = pd.read_csv("../datasets/data_cleaning_sample.csv")

In [2]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
#Check for Missing Data:
df.isnull()  # True for NaNs

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [7]:
df.isnull().sum()        # Count missing value per column

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [22]:
#Drop Missing Data
df1=df.dropna() # Drop rows with *any* missing values or NaN values
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [9]:
df.dropna(axis=1)        # Drop columns with missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [11]:
df1 #because we want updated table:

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [22]:
df.fillna(0)  # Replace NaN with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [23]:
df.ffill()  #forward fill: like upar se neeche aaye like in age column to jo latest hoga vo print ho jayega is NAN value mein

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [24]:
df.bfill() ##backward fill: like  neeche se upar aaye like in age column to jo latest hoga vo print ho jayega is NAN value mein

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [25]:
#Detecting & Removing Duplicates: df.duplicated() returns a boolean Series where: True means that row is a duplicate of a previous row. False means it's the first occurrence (not a duplicate yet).

df.duplicated()          # True for duplicates

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [13]:
df.drop_duplicates() #Remeve duplicate rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [27]:
#Type Conversions with .astype(): Convert column data types:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8 non-null      object
 1   Age        6 non-null      float64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  8 non-null      object
dtypes: float64(1), object(5)
memory usage: 564.0+ bytes

In [3]:
df["Age"] = df["Age"].astype(int) #as age is float64 but we need integer so typecasted

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

**IntCastingNaNError: Cannot convert df table, as non-finite values (NA or inf) are present in df table,especially age column kyunki age ka nikalna tha but vahan NAN value thi, which cannot typecasted into integer. 
so df1=df.dropna() se jo df1 table baaaya tha vo use krenge as usmein hamne sari missing values and NaN values reove krdi this
and also we make a copy out of it**

In [24]:
df1["Age"] = df1["Age"].astype(int).copy() #as humne pehle df1=df.dropna() # Drop rows with *any* missing values or NaN values

C:\Users\adity\AppData\Local\Temp\ipykernel_11064\4124025184.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Age"] = df1["Age"].astype(int).copy() #as humne pehle df1=df.dropna() # Drop rows with *any* missing values or NaN values

In [20]:
df1

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [37]:
df1.info()  #now in "age" column, datatype of df1 table is changed from "float64" to "int 64"

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int64
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int64(1), object(5)
memory usage: 280.0+ bytes

In [26]:
#Applying Functions: 

#1. .apply() → Apply any function to rows or columns

df1["Age Group"] = df1["Age"].apply(lambda x: "Adult" if x >= 25 else "Minor").copy()

C:\Users\adity\AppData\Local\Temp\ipykernel_11064\709542283.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Age Group"] = df1["Age"].apply(lambda x: "Adult" if x >= 25 else "Minor").copy()

In [27]:
df1 #new column with age group

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai      M  david@example.com  12-11-2019     Minor
6  Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7  Alice   25     New York      F  alice@example.com  01-05-2021     Adult

In [29]:
#2. .map() → Element-wise mapping for Series
gender_map = {"M": "Male", "F": "Female"}
df1["Gender"] = df1["Gender"].map(gender_map).copy()

C:\Users\adity\AppData\Local\Temp\ipykernel_11064\2983249142.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Gender"] = df1["Gender"].map(gender_map).copy()

In [30]:
df1

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22       Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7  Alice   25     New York  Female  alice@example.com  01-05-2021     Adult

In [31]:
#3. .replace() → Replace specific values
df1["City"] = df1["City"].replace({"New York": "New Yorkery", "Mumbai": "New Mumbai"})

C:\Users\adity\AppData\Local\Temp\ipykernel_11064\136149408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["City"] = df1["City"].replace({"New York": "New Yorkery", "Mumbai": "New Mumbai"})

In [32]:
df1

    Name  Age         City  Gender              Email   Join Date Age Group
0  Alice   25  New Yorkery  Female  alice@example.com  01-05-2021     Adult
2    Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4  David   22   New Mumbai    Male  david@example.com  12-11-2019     Minor
6  Alice   25  New Yorkery  Female  alice@example.com  01-05-2021     Adult
7  Alice   25  New Yorkery  Female  alice@example.com  01-05-2021     Adult