In [2]:
import pandas as pd
df = pd.read_csv("../datasets/data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df[["Actor", "Year", "BoxOffice(INR Crore)"]] #selecting rows or columns:Multiple columns (as DataFrame) but know that they are case sensitive

                 Actor  Year  BoxOffice(INR Crore)
0       Shah Rukh Khan  2023                  1050
1          Salman Khan  2017                   565
2           Aamir Khan  2016                  2024
3        Ranbir Kapoor  2022                   431
4        Ranveer Singh  2018                   585
5   Ayushmann Khurrana  2018                   111
6        Rajkummar Rao  2018                   180
7       Hrithik Roshan  2019                   475
8         Akshay Kumar  2019                   318
9        Kartik Aaryan  2022                   266
10        Varun Dhawan  2017                   201
11       Vicky Kaushal  2019                   342

In [5]:
#Selecting Rows by Index
df.loc[1] # Second row (by label)

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [6]:
df.iloc[1] #second row by position

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [7]:
#Select Specific Rows and Columns
df.loc[0:2, ["Actor", "Genre","Film","Year"]] # Rows 0 to 2, selected columns and one more thing aap koi bhi column likh skte ho us according values aa jaayengi

            Actor      Genre             Film  Year
0  Shah Rukh Khan     Action          Pathaan  2023
1     Salman Khan     Action  Tiger Zinda Hai  2017
2      Aamir Khan  Biography           Dangal  2016

In [8]:
df.iloc[0:2, 0:2]              # Rows and cols by index position

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [24]:
# One major difference between iloc and loc slicing is that ki loc mein last vaala include hoga but iloc mein nhi
#like df.loc[0:2, ["Name", "Film", "Genre"]] mein 0,1,2 teeno rows aayenge but
#df.iloc[0:2,0:2] mein sirf 0 and 1 row aayegi

In [14]:
df.value_counts()

Actor               Film                      Year  Genre            BoxOffice(INR Crore)  IMDb
Aamir Khan          Dangal                    2016  Biography        2024                  8.4     1
Akshay Kumar        Good Newwz                2019  Comedy           318                   7.0     1
Ayushmann Khurrana  Andhadhun                 2018  Thriller         111                   8.3     1
Hrithik Roshan      War                       2019  Action           475                   6.5     1
Kartik Aaryan       Bhool Bhulaiyaa 2         2022  Horror Comedy    266                   5.9     1
Rajkummar Rao       Stree                     2018  Horror Comedy    180                   7.5     1
Ranbir Kapoor       Brahmastra                2022  Fantasy          431                   5.6     1
Ranveer Singh       Padmaavat                 2018  Historical       585                   7.0     1
Salman Khan         Tiger Zinda Hai           2017  Action           565                   6.0     1
Shah Rukh Khan      Pathaan                   2023  Action           1050                  7.2     1
Varun Dhawan        Badrinath Ki Dulhania     2017  Romantic Comedy  201                   6.1     1
Vicky Kaushal       Uri: The Surgical Strike  2019  Action           342                   8.2     1
Name: count, dtype: int64

In [9]:
#Filtering with Conditions: 
#a. Simple Condition
df[df["Year"] > 2018]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
#b. Multiple Conditions (AND / OR)
df[(df["Year"]>2018) & (df["IMDb"]>7)] #and operator

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [11]:
df[(df["Year"]>2018) | (df["IMDb"]>7)] #or operator

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
#Querying with .query(): it makes more convinient code
df.query("Year> 2018 and IMDb> 7")  #here "and operator(&)" is replaced with "and"

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [13]:
df.query("Year>2018 or IMDb>7")    #here "or operator(|)" is replaced with "or"

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [15]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
#Exploratory Data Analysi: most import for data:

df.head()  # First 5 rows

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

In [18]:
df.tail() # Last 5 rows

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [19]:
df.info()  # Column info: types, non-nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     object
 1   Film                  12 non-null     object
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     object
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

In [20]:
df.describe()   # Stats for numeric columns

              Year  BoxOffice(INR Crore)       IMDb
count    12.000000             12.000000  12.000000
mean   2019.000000            545.666667   6.975000
std       2.215647            528.535942   0.981766
min    2016.000000            111.000000   5.600000
25%    2017.750000            249.750000   6.075000
50%    2018.500000            386.500000   7.000000
75%    2019.750000            570.000000   7.675000
max    2023.000000           2024.000000   8.400000

In [23]:
# Use .head() , .info() , .describe() to quickly explore any dataset