In [2]:
import pandas as pd
#load dataframe
data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Maths" : [85, 78, 92],
    "Science" : [90, 82, 89],
    "English" : [88, 85, 94]
}
df = pd.DataFrame(data)
print(df)

      Name  Maths  Science  English
0    Alice     85       90       88
1      Bob     78       82       85
2  Charlie     92       89       94

**1. Using melt() : The melt() method in Pandas is used to unpivot a DataFrame from wide format to long format.**

**Parameters:**

id_vars : The columns that you want to keep fixed (these columns will remain as identifiers).

value_vars : The columns you want to unpivot (the ones you want to “melt”into a single column).

var_name : The name to use for the new column that will contain the names ofthe melted columns (default is 'variable' ).

value_name : The name to use for the new column that will contain the valuesfrom the melted columns (default is 'value' ).

col_level : Used for multi-level column DataFrames.

In [3]:
df1 = df.melt(id_vars = ["Name"], value_vars = ["Maths","Science", "English"], var_name = "Subject", value_name = "Score")

In [3]:
df1

      Name  Subject  Score
0    Alice    Maths     85
1      Bob    Maths     78
2  Charlie    Maths     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

**2. Using pivot():The pivot() function in Pandas is used to reshape data, specifically to turn long format data into wide-format data. This is the reverse operation of melt().Using pivot() to reshape it into wide format:**

**Parameters:**

index : The column whose unique values will become the rows of the newDataFrame.

columns : The column whose unique values will become the columns of thenew DataFrame.

values : The column whose values will fill the new DataFrame. These will become the actual data (values in the table).

In [4]:
df2 = df1.pivot(index="Name", columns="Subject", values="Score")

In [5]:
df2

Subject  English  Maths  Science
Name
Alice         88     85       90
Bob           85     78       82
Charlie       94     92       89

In [6]:
#now work on real dataset:

death = pd.read_csv("time_series_covid19_deaths_global.csv")
confirmed = pd.read_csv("time_series_covid19_confirmed_global.csv")

In [7]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [9]:
confirmed.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [15]:
# dono datasets kaafi wide hai so humein inhe melt krna hoga and then merge:

death = death.melt(id_vars= ["Province/State", "Country/Region", "Lat", "Long"], var_name = "Date", value_name = "Death_count")
confirmed = confirmed.melt(id_vars= ["Province/State", "Country/Region", "Lat", "Long"], var_name = "Date", value_name = "confirm_count")

In [16]:
death.head()

  Province/State Country/Region       Lat       Long      Date Death_count
0            NaN    Afghanistan  33.93911  67.709953  variable     1/22/20
1            NaN        Albania  41.15330  20.168300  variable     1/22/20
2            NaN        Algeria  28.03390   1.659600  variable     1/22/20
3            NaN        Andorra  42.50630   1.521800  variable     1/22/20
4            NaN         Angola -11.20270  17.873900  variable     1/22/20

In [17]:
confirmed.head()

  Province/State Country/Region       Lat       Long      Date confirm_count
0            NaN    Afghanistan  33.93911  67.709953  variable       1/22/20
1            NaN        Albania  41.15330  20.168300  variable       1/22/20
2            NaN        Algeria  28.03390   1.659600  variable       1/22/20
3            NaN        Andorra  42.50630   1.521800  variable       1/22/20
4            NaN         Angola -11.20270  17.873900  variable       1/22/20

In [ ]:
# as now data is visible, now merge it 

confirmed.merge(death, on = ["Province/State", "Country/Region", "Lat", "Long", "Date"])[["Country/Region","Date", "Death_count", "confirm_count"]]