**Now export functions in pandas:**
- to csv
- to excel
- to html
- to json
- to sql

In [2]:
import pandas as pd
df = pd.DataFrame()  #empty dataframe jiske andar hum apni  files daalenge

**a. export as to_csv:**

In [3]:
df1 = pd.read_csv("../datasets/batter.csv")
df1.head()

      batter  runs        avg  strike_rate
0    V Kohli  6634  36.251366   125.977972
1   S Dhawan  6244  34.882682   122.840842
2  DA Warner  5883  41.429577   136.401577
3  RG Sharma  5881  30.314433   126.964594
4   SK Raina  5536  32.374269   132.535312

In [4]:
df1.groupby("batter")["runs"].sum()

batter
A Ashish Reddy     280
A Badoni           161
A Chandila           4
A Chopra            53
A Choudhary         25
                  ...
Yash Dayal           0
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2754
Z Khan             117
Name: runs, Length: 605, dtype: int64

In [5]:
#above is series right now , so convert in dataframe:

temp = df1.groupby("batter")["runs"].sum().reset_index()
temp

             batter  runs
0    A Ashish Reddy   280
1          A Badoni   161
2        A Chandila     4
3          A Chopra    53
4       A Choudhary    25
..              ...   ...
600      Yash Dayal     0
601   Yashpal Singh    47
602     Younis Khan     3
603    Yuvraj Singh  2754
604          Z Khan   117

[605 rows x 2 columns]

In [6]:
#now export above table in new csv file:

temp.to_csv("batsman_run.csv", index = False)   #ab ek new csv file generate ho gyi batsman_run.csv naam se

**b. export as to_excel:**

In [15]:
df1.groupby("batter")["runs"].sum().reset_index()

             batter  runs
0    A Ashish Reddy   280
1          A Badoni   161
2        A Chandila     4
3          A Chopra    53
4       A Choudhary    25
..              ...   ...
600      Yash Dayal     0
601   Yashpal Singh    47
602     Younis Khan     3
603    Yuvraj Singh  2754
604          Z Khan   117

[605 rows x 2 columns]

In [16]:
#now export above table in new excel file:

temp.to_csv("batsman_run.xlsx", index = False)   #ab ek new csv file generate ho gyi batsman_run.xlsx naam se

**c. export as to json:**

In [21]:
df2 = df1.groupby(["batter", "runs"])["strike_rate"].sum().unstack()
df2

runs,0,1,2,3,4,5,6,7,8,9,...,4377,4954,4978,4997,5181,5536,5881,5883,6244,6634
batter,,,,,,,,,,,,,,,,,,,,,
A Ashish Reddy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Badoni,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Chandila,NaN,NaN,NaN,NaN,57.142857,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Chopra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Choudhary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yash Dayal,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yashpal Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Younis Khan,NaN,NaN,NaN,42.857143,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yuvraj Singh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z Khan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df2.to_json("batsmen.json")  #nnow export to json

**d. export as sql:**
**uske liye fir new tab mein link pe localhost/phpmyadmin/ enter krke page open krna hai**
**and then create new database named "batters" jisme tum yeh sql file export kroge**

In [25]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [26]:
import pymysql
from sqlalchemy import create_engine   # yeh 2 libraries bahut imp hain sql export mein

In [32]:
engine = create_engine("mysql+pymysql://root:@localhost/batters") #fir aapko ek engine object banana hai

#syntax: //(root):(password)@(url)/(database)  here: password is bothing isliye kuch nhi like and database hamne batters ke naam se banaya hai

In [33]:
df1.to_sql("Batsman_data", con = engine, if_exists = "append") #now if you see in localhost page, tum dekhoge ki vahaan batters databases mein Batsman_data naam ki sql file add ho gyi hai

C:\Users\adity\AppData\Local\Temp\ipykernel_9612\590923077.py:1: UserWarning: The provided table name 'Batsman_data' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df1.to_sql("Batsman_data", con = engine, if_exists = "append")

605

In [34]:
temp.to_sql("Batsman_run", con = engine, if_exists = "append") 
df2.to_sql("unstack_batsman", con = engine, if_exists = "append")

C:\Users\adity\AppData\Local\Temp\ipykernel_9612\3863616268.py:1: UserWarning: The provided table name 'Batsman_run' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  temp.to_sql("Batsman_run", con = engine, if_exists = "append")

605

**ab aap dekhoge localhost page mein all 3 files were export named Batsman_data, Batsman_run and unstack_batsman**